prometheus:
  deployment:
    name: 
    replicas: 2
  service:
    type: NodePort
    port: 9090
  container:
    name: 
    resources: {}
      # limits:
      #   memory: 1024Mi
      #   cpu: 500m
      # requests:
      #   memory: 512Mi
      #   cpu: 100m
  image:
    repository: bob4inski/prometheus
    pullPolicy: IfNotPresent
    tag: "latest"
  hpa:
    enabled: false
    name:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: false

